/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper */

#ifndef _Included_com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper
#define _Included_com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper
 * Method:    nativeProcess
 * Signature: (JJJD)V
 */
JNIEXPORT void JNICALL Java_com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper_nativeProcess
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble);

/*
 * Class:     com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper
 * Method:    nativeGetDesiredRotation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper_nativeGetDesiredRotation
  (JNIEnv *, jclass);

/*
 * Class:     com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wheelphone_navigator_helpers_TrackerAvoiderNativeWrapper_nativeRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
