/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper */

#ifndef _Included_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
#define _Included_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
 * Method:    nativeProcess
 * Signature: (JJJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper_nativeProcess
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
 * Method:    nativeGetDesiredRotation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper_nativeGetDesiredRotation
  (JNIEnv *, jclass);

/*
 * Class:     com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
 * Method:    nativeIsFollowingTarget
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper_nativeIsFollowingTarget
  (JNIEnv *, jclass);

/*
 * Class:     com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
 * Method:    nativeTargetReached
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper_nativeTargetReached
  (JNIEnv *, jclass);

/*
 * Class:     com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
 * Method:    nativeUpdateRangeBounds
 * Signature: ([D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper_nativeUpdateRangeBounds
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
 * Method:    nativeAddTarget
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper_nativeAddTarget
  (JNIEnv *, jclass);

/*
 * Class:     com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wheelphone_navigator_helpers_MotionTrackerNativeWrapper_nativeRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
