/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wheelphone_facetrack_FaceDetector */

#ifndef _Included_com_wheelphone_facetrack_FaceDetector
#define _Included_com_wheelphone_facetrack_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wheelphone_facetrack_FaceDetector
 * Method:    nativeClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wheelphone_facetrack_FaceDetector_nativeClassInit
  (JNIEnv *, jclass);

/*
 * Class:     com_wheelphone_facetrack_FaceDetector
 * Method:    fft_initialize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_wheelphone_facetrack_FaceDetector_fft_1initialize
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wheelphone_facetrack_FaceDetector
 * Method:    fft_detect
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_wheelphone_facetrack_FaceDetector_fft_1detect
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wheelphone_facetrack_FaceDetector
 * Method:    fft_get_face
 * Signature: (Lcom/wheelphone/facetrack/FaceDetector/Face;I)V
 */
JNIEXPORT void JNICALL Java_com_wheelphone_facetrack_FaceDetector_fft_1get_1face
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wheelphone_facetrack_FaceDetector
 * Method:    fft_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wheelphone_facetrack_FaceDetector_fft_1destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
